# Generated by Django 3.1.1 on 2021-01-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='talla',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
