# Generated by Django 2.2.17 on 2021-02-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210102_1521'),
        ('blog', '0002_auto_20210102_0248'),
    ]

    operations = [
    ]
